test-word: Saibal Ghosh SKG
test:
  rabbitmq:
     host: localhost
    port: 5672
     username: fdc
     password: fdc
endpoints:
  shutdown:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  #instance:
   # leaseRenewalIntervalInSeconds: 1
    #leaseExpirationDurationInSeconds : 2